# SPDX-License-Identifier: GPL-2.0-or-later
#
# Copyright (c) 2025 Western Digital Corporation or its affiliates.
#
# Authors: Dennis Maisenbacher (dennis.maisenbacher@wdc.com)

name: "KubeVirt action"
description: "Spwaning a KubeVirt VM in your k8s cluster via ARC"
author: "Dennis Maisenbacher"
inputs:
  kernel_version:
    description: "Linux kernel version that the VM should startup with."
    required: true
  run_cmds:
    description: "Commands that should be executed within the VM"
    required: true
  vm_artifact_upload_dir:
    description: "VM directory of artifacts to upload"
    required: false

outputs:
  stdout:
    description: "stdout of the run_cmds"
    value: ${{ steps.run.outputs.stdout }}

runs:
  using: "composite"
  steps:
    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
    - name: Install required tools
      run: ${GITHUB_ACTION_PATH}/entrypoint.sh install_requirements
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
    - id: run
      name: Run cmds in VM
      run: ${GITHUB_ACTION_PATH}/entrypoint.sh run_ssh_cmds
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
        INPUT_KERNEL_VERSION: ${{ inputs.kernel_version }}
        INPUT_RUN_CMDS: ${{ inputs.run_cmds }}
    - name: Create timestamp env var for artifact uploads
      shell: bash
      run: |
        ts=$(date +'%Y%m%d-%H%M%S')
        echo "TS=$ts" >> $GITHUB_ENV
      if: ${{ always() }}
    - name: Extract test artifacts for upload
      id: extract_artifact
      run: ${GITHUB_ACTION_PATH}/entrypoint.sh extract_test_artifacts_for_upload "${{ inputs.vm_artifact_upload_dir }}"
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
      if: ${{ always() && inputs.vm_artifact_upload_dir != '' }}
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: artifact-${{ env.TS }}
        path: |
          ./artifacts
      if: ${{ steps.extract_artifact.outcome == 'success' }}
    - name: Unpack kernel artifacts from VM to runner pod
      id: unpack
      continue-on-error: true
      run: ${GITHUB_ACTION_PATH}/entrypoint.sh extract_kernel_artifacts
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
        INPUT_KERNEL_VERSION: ${{ inputs.kernel_version }}
      if: ${{ always() }}
    - name: Upload kernel artifacts
      uses: actions/upload-artifact@v4
      with:
        name: kernel-artifact-${{ inputs.kernel_version }}-${{ env.TS }}
        path: |
          ~/kernel-artifacts
      if: ${{ steps.unpack.outcome == 'success' }}
    - name: VM cleanup
      shell: bash
      run: ${GITHUB_ACTION_PATH}/entrypoint.sh cleanup_vm
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
      if: ${{ always() }}

branding:
  icon: "monitor"
  color: "gray-dark"
