# SPDX-License-Identifier: GPL-2.0-or-later
#
# Copyright (c) 2025 Western Digital Corporation or its affiliates.
#
# Authors: Dennis Maisenbacher (dennis.maisenbacher@wdc.com)

name: "KubeVirt action"
description: "Spwaning a KubeVirt VM in your k8s cluster via ARC"
author: "Dennis Maisenbacher"
inputs:
  kernel_version:
    description: "Linux kernel version that the VM should startup with."
    required: true
  run_cmds:
    description: "Commands that should be executed within the VM"
    required: true
  vm_artifact_upload_dir:
    description: "VM directory of artifacts to upload"
    required: false

outputs:
  stdout:
    description: "stdout of the entrypoint including the executing run_cmds"
    value: ${{ steps.entrypoint.outputs.stdout }}

runs:
  using: "composite"
  steps:
    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
    - id: entrypoint
      name: Run entrypoint.sh
      run: ${GITHUB_ACTION_PATH}/entrypoint.sh
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
        INPUT_KERNEL_VERSION: ${{ inputs.kernel_version }}
        INPUT_RUN_CMDS: ${{ inputs.run_cmds }}
    - name: scp artifacts from VM to runner pod
      shell: bash
      run: |
        source vars.sh
        mkdir artifacts
        ./virtctl scp "${ssh_options[@]}" -r ${vm_user}@${vm_name}:/home/${vm_user}/${{ inputs.vm_artifact_upload_dir }} artifacts
      if: ${{ always() && inputs.vm_artifact_upload_dir != '' }}
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        path: |
          ./artifacts
      if: ${{ always() && inputs.vm_artifact_upload_dir != '' }}
    - name: VM cleanup
      shell: bash
      run: |
        ./kubectl delete -f vm.yml
      if: ${{ always() }}

branding:
  icon: "monitor"
  color: "gray-dark"
